### ISSUE TITLE
[Demo] Wrong data in snippet for InputAutocomplete

### ISSUE THREAD

**Issue by dmitrymalakhov** [bcrumbs/reactackle#34]
Options in the snippet not match the data in autocomplete

![screenshot from 2017-08-09 11-14-50](https://user-images.githubusercontent.com/2477267/29115548-b5d1ac42-7d00-11e7-93e5-a710da871ad9.png)

![screenshot from 2017-08-09 11-14-54](https://user-images.githubusercontent.com/2477267/29115558-bd276fc2-7d00-11e7-9c09-b16b25afad86.png)

**Comment by netmenya** [comment]
done
