### ISSUE TITLE
Sidebar not autoscrolling

### ISSUE THREAD

**Issue by kodepareek** [bcrumbs/reactackle#81]
Hi guys. The sidebar is rendering without autoscroll and most of my elements are going below the page. What would be a way to handle this?

Cannot see any way to set props here either

**Comment by kodepareek** [comment]
Nevermind. Was using it absolutely wrong. Needs documentation. Might attempt a PR into docs once I get this fixed.

**Comment by netmenya** [comment]
Hi!
Sorry to hear that you have difficulties with Reactackle. I completely agree that our docs lack information…like a lot. So we’d be very grateful for any contributions. Thank you!

Here’re few notes about how <Sidebar /> works. We’ll add it to the docs shortly. Would you like to add anything to it?

Sidebar consists of 2 wrappers: Sidebar (the top one) and SidebarBox.
Sidebar-wrapper is positioned relatively to set proper boundaries for the SidebarBox to avoid using JS for the most cases. As SidebarBox is now positioned fixedly you should make sure that Sidebar (top wrapper) height completely fits window height. We'll probably add the possibility to scroll Sidebar with the screen a bit later.

In Reactackle we have an <App /> component with few regions: Top, Main and Bottom. <Sidebar /> is designed to be placed in <MainRegion /> - this helps to set <Sidebar /> height and to make sure that main content of the page (component <Content />), placed aside <Sidebar />, will change its width whether <Sidebar /> is collapsed or not. To make <Sidebar /> fit windows height wou should set to set App's prop.fixed to true. It'll work with following restrictions: 

1. If you don’t have anything above <Sidebar /> or have anything with constant height, <Sidebar /> is going to work on its own.
1. If you’re going to temporarily add anything above Sidebar or have the component which height varies, you'll need to dynamically change top coordinate of the SidebarBox. Also, as SidebarBox is positioned fixedly, you’ll need to set a height for SidebarBox, for example, equals to ‘100vh - ${topOffset + bottomOffset}’, to make sure Sidebar fits the screen height.
